### ISSUE TITLE
How to remove the operation icons 

### ISSUE THREAD

**Issue by priyankab95** [ParadeTo/vue-tree-list#32]
I want to remove the operational icons which appear while hovering onto it.
It is not feasible to include the flags in every node of the tree.

**Comment by DaanMoura** [comment]
An workaround is hiding the slot of operation with css

For example:
```html
<span slot="addLeafNodeIcon" class="invisible" />
```

```css
.invisible {
    visibility: hidden;
    width: 0;
    height: 0;
}
```

Is not the perfect way, but I think that is better than include flags in every node, since I can't edit all this flag when a new tree node is created.
